name: iOS CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
          xcode-version: '15.0.1'
    
    - name: Resolve Swift packages
      run: |
        xcodebuild -resolvePackageDependencies -scheme PayStackAssignment

    - name: Clean and build the app
      run: |
        xcodebuild clean -workspace PayStackAssignment.xcodeproj -scheme PayStackAssignment -configuration Release

    - name: Build the app
      run: |
        xcodebuild -workspace PayStackAssignment.xcodeproj -scheme PayStackAssignment -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build

    - name: Run tests
      run: |
        xcodebuild test -workspace PayStackAssignment.xcodeproj -scheme PayStackAssignment -destination 'platform=iOS Simulator,name=iPhone 15' | tee result.log | tail -n 20
        
